# Simplifications consts
SIMPLE_TURKER_IDS = list(range(8))

# contraction consts
CONTRACTION_DICT = {  # "aight": "alright",
    # "ain't": "am not / is not / are not / has not / have not / did not",
    # "amn't": "am not",
    "aren't": "are not",
    "can't": "cannot / can not",
    # "'cause": "because",
    "could've": "could have",
    "couldn't": "could not",
    # "couldn't've": "could not have",
    # "daren't": "dare not / dared not",
    # "daresn't": "dare not",
    # "dasn't": "dare not",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",  # / does not",
    # "dunno": 	"don't know / do not know",
    # "d'ye": 	"do you / did you",
    # "e'er": 	"ever",
    # "'em": "them",
    "everybody's": "everybody is",
    "everyone's": "everyone is",
    # "finna": "fixing to / going to",
    # "g'day": "good day",
    # "gimme": "give me",
    # "giv'n": "given",
    # "gonna": "going to",
    # "gon't": "go not",
    # "gotta": "got to",
    "hadn't": "had not",
    # "had've": "had have",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he had / he would",  # / he did",
    "he'll": "he will",  # he shall /
    "he's": "he has / he is",
    "here's": "here is",
    # "he've": "he have",
    "how'd": "how did / how would",
    # "howdy": "how do you do / how do you fare",
    "how'll": "how will",
    # "how're": "how are",
    "how's": "how has / how is",  # / how does
    "I'd": "I had / I would / I should",  # / I did",
    # "I'd've": "I would have",
    "I'll": "I shall / I will",
    "I'm": "I am",
    # "I'm'a": "I am about to",
    # "I'm'o": "I am going to",
    # "innit": "is it not",
    "I've": "I have",
    "isn't": "is not",
    "it'd": "it would / it had",  # / it did",
    "it'll": "it shall / it will",
    "it's": "it has / it is",
    # "iunno": "I don't know",
    # "kinda": "kind of",
    # "let's": "let us",
    # "ma'am": "madam",
    # "mayn't": "may not",
    # "may've": "may have",
    # "methinks": "me thinks",
    "mightn't": "might not",
    # "might've": "might have",
    "mustn't": "must not",
    # "mustn't've": "must not have",
    "must've": "must have",
    "needn't": "need not",
    # "nal": "and all",
    # "ne'er": 	"never",
    # "o'clock": "of the clock",
    # "o'er": 	"over",
    # "ol'": "old",
    "oughtn't": "ought not",
    # "'s": 	"is, has, does, or us",
    # "shalln't": "shall not",
    "shan't": "shall not",
    "she'd": "she had / she would",  # / she did",
    "she'll": "she shall / she will",
    "she's": "she has / she is",
    "should've": "should have",
    "shouldn't": "should not",
    # "shouldn't've": "should not have",
    "somebody's": "somebody has / somebody is",
    "somebody'd": "somebody would / somebody had",  # / somebody did
    "somebody'll": "somebody will",
    "someone's": "someone has / someone is",
    "someone'd": "someone would / someone had",  # / someone did
    "someone'll": "someone will",
    "something's": "something has / something is",
    "something'd": "something would / something had",  # / something did
    "something'll": "something will",
    # "so're": "so are",
    "that'll": "that will",  # that shall
    # "that're": "that are",
    "that's": "that has / that is",
    "that'd": "that would / that had",
    "there'd": "there had / there would",
    "there'll": "there shall / there will",
    # "there're": "there are",
    "there's": "there has / there is",
    "there've": "there have",
    "these're": "these are",
    # "these've": "these have",
    "they'd": "they had / they would",  # / they did
    "they'll": "they shall / they will",
    "they're": "they are",  # / they were",
    "they've": "they have",
    # "this's": "this has / this is",
    # "those're": "those are",
    # "those've": "those have",
    # "'tis": 	"it is",
    # "to've": "to have",
    # "'twas": "it was",
    # "wanna": "want to",
    "wasn't": "was not",
    "we'd": "we had / we would / we should",  # / we did",
    # "we'd've": "we would have",
    "we'll": "we shall / we will",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    # "what'd": "what would",  # did
    # "what'll": "what shall / what will",
    # "what're": "what are/what were",
    "what's": "what has / what is / what does",
    # "what've": "what have",
    "when's": "when has / when is",
    # "where'd": "where would / where had",  # where did
    # "where'll": "where shall / where will",
    # "where're": "where are",
    # "where's": "where has / where is / where does",
    # "where've": "where have",
    # "which'd": "which had / which would",
    # "which'll": "which shall / which will",
    # "which're": "which are",
    # "which's": "which has / which is",
    # "which've": "which have",
    "who'd": "who would / who had",  # / who did",
    # "who'd've": "who would have",
    "who'll": "who will",  # who shall /
    # "who're": "who are",
    "who's": "who has / who is",  # / who does
    # "who've": "who have",
    # "why'd": "why did",
    # "why're": "why are",
    # "why's": "why has / why is / why does",
    # "willn't": "will not",
    "won't": "will not",
    # "wonnot": "will not",
    "would've": "would have",
    "wouldn't": "would not",
    # "wouldn't've": "would not have",
    # "y'all": "you all",
    # "y'all'd've": "you all would have",
    # "y'all'd'n've": "you all would not have",
    # "y'all're": "you all are",
    # "y'at": "you at",
    "you'd": "you had / you would",  # / you did",
    "you'll": "you shall / you will",
    "you're": "you are",
    "you've": "you have"}
# "noun's": "noun is",
# "noun(s)'re": "noun(s) are"}

# number substitution constants
# https://en.wikipedia.org/wiki/Template:Convert/list_of_units
REDDIT_SKIP_COMMENTS = [" ", "", " [removed] ", "[ removed ]", "[removed]", "[ deleted ]", "[deleted]", " [deleted] ",
                        "\n",
                        " \n", "\n ", " \n "]
NSUBS_PATH = "../Data/Experiment-Results/annotations/00_nsubs_sentences.txt"
NSUBS_TRANSLATED = "../Data/Experiment-Results/annotations/00_nsubs_translated_sentences.txt"
